name: build
on:
  push:
  pull_request:

jobs:

  build:
    name: Configuration
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 75
      VARIABLE: 'FOO'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Foo
        env: 
          FOO: ${{ secrets[env.VARIABLE] }}
        run: |
          VALUE=$FOO 
          JSON=$(echo $FOO | jq ".Foo")
          echo "Foo - $FOO"
          echo $(echo $FOO | ./bin/set-kvp.sh "Hello" "World")



 