name: build
on:
  push:
  pull_request:

jobs:

  build:
    name: Configuration
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 75
      VARIABLE: 'FOO'
    steps:
      - name: Get Foo
        env: 
          FOO: ${{ secrets['FOO'] }}
        run: |
          VALUE=$FOO 
          JSON=$(echo $FOO | jq ".Foo")
          echo "Foo - $FOO"
          echo $(echo $FOO | ./bin/set-kvp.sh "Hello" "World")
          


 