name: build
on:
  push:
  pull_request:

jobs:

  build:
    name: Configuration
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 75
      VARIABLE: 'FOO'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: ./.github/actions/say-hello@v1
        with:
          name: OctoCat

      - name: Get Foo
        env: 
          FOO: ${{ secrets[env.VARIABLE] }}
          GITHUB_TOKEN: ${{secrets.PAT}}
        run: |
          VALUE=$FOO 
          JSON=$(echo $FOO | jq ".Foo")
          echo "Foo - $FOO"
          echo $(echo $FOO | ./bin/set-kvp.sh "Hello" "World")
          echo "Repository ${{ github.repository }}"
          gh secret set VERSIONS -b '{ "A": "B" }' -R ${{github.repository}}
      - name: Set version
        uses: ./.github/actions/set-version@v1
        with:
          githubToken: ${{secrets.PAT}}
          name: "test"



# gh secret set VERSIONS -b "{}" -R nick-hadfield/test
#echo {{github.token}} | gh auth login --with-token