name: build
on:
  push:
  pull_request:

jobs:

  build:
    name: Configuration
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 75
      FOO: ${{ secrets.FOO }}
    steps:
      - name: Get Foo
        run: |
          VALUE=$FOO 
          JSON=$(jq "$FOO" ".Foo" -r)
          echo "Foo - $FOO"
          echo "Json - $JSON"


 