name: build
on:
  push:
  pull_request:

jobs:

  build:
    name: Configuration
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 75
      VARIABLE: 'FOO'
      FOO: ${{ secrets[env.VARIABLE] }}
    steps:
      - name: Get Foo
        run: |
          VALUE=$FOO 
          JSON=$(echo $FOO | jq ".Foo")
          echo "Foo - $FOO"
          echo "Json - $JSON"


 